"""
Auto-Fix 循环模块

负责代码生成、测试、修复的完整闭环编排
"""

import asyncio
import logging
import time
from typing import Dict, List, Optional, Any
from pathlib import Path

from app.agents.coder import coder_agent
from app.agents.tester import test_agent
from app.agents.repairer import RepairerAgent
from app.service.sandbox_tools import write_file as sandbox_write_file, exec_command, read_file
from app.service.code_executor import CodeExecutorService
from app.service.file_write_handler import file_write_handler
from app.service.import_sanitizer import ImportSanitizer
from app.service.error_context_parser import parse_error_context
from app.core.code_validator import code_validator
from app.core.event_bus import emit_log
from app.core.sse_log_buffer import push_log
from app.core.config import settings
from app.core.resilience import ResilienceManager, RetryConfig, CircuitBreakerOpenError

logger = logging.getLogger(__name__)


class AutoFixLoop:
    """
    Auto-Fix 循环编排器

    实现 生成 -> 运行 -> 报错 -> 修复 的闭环迭代
    """

    MAX_FIX_RETRIES = 3  # 最大自动修复次数

    def __init__(self):
        self.total_input_tokens = 0
        self.total_output_tokens = 0
        # 【智能重试】初始化测试运行重试执行器
        self._test_retry_executor = ResilienceManager.get_executor(
            name="test_runner",
            **RetryConfig.TEST_RUN
        )

    async def execute(
        self,
        design_output: Dict,
        affected_files: List[str],
        pipeline_id: int,
        workspace_path: str,
        sandbox_port: Optional[int] = None,
        error_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        执行带自动修复的多 Agent 代码生成

        【改造】不再传入预加载的 target_files，改为传入 affected_files 列表
        CoderAgent 使用工具按需读取文件内容
        """
        current_error_context = error_context
        attempt = 0
        last_code_output = None

        self.total_input_tokens = 0
        self.total_output_tokens = 0
        start_time = time.time()

        # ★ 读取测试文件（供参考，不强制 AI 使用）
        test_files = await self._read_test_files(pipeline_id, affected_files)

        if test_files:
            await push_log(
                pipeline_id,
                "info",
                f"📄 找到 {len(test_files)} 个相关测试文件，将提供给 AI 参考",
                stage="CODING"
            )

        while attempt <= self.MAX_FIX_RETRIES:
            if attempt > 0:
                await push_log(
                    pipeline_id,
                    "warning",
                    f"检测到测试失败，开始第 {attempt} 次自动修复...",
                    stage="CODING"
                )

            # 1. Coder 生成代码
            code_result = await self._execute_code_agent(
                design_output,
                test_files,
                pipeline_id=pipeline_id,
                error_context=current_error_context
            )

            self.total_input_tokens += code_result.get("input_tokens", 0) or 0
            self.total_output_tokens += code_result.get("output_tokens", 0) or 0

            if code_result.get("success") and code_result.get("code_output"):
                last_code_output = code_result["code_output"]

            if not code_result["success"]:
                logger.error(f"AutoFixLoop: CoderAgent 执行失败", extra={
                    "pipeline_id": pipeline_id,
                    "attempt": attempt,
                    "error": code_result["error"],
                    "total_input_tokens": self.total_input_tokens,
                    "total_output_tokens": self.total_output_tokens
                })
                return {
                    "success": False,
                    "error": f"Code generation failed: {code_result['error']}",
                    "output": None,
                    "attempt": attempt,
                    "input_tokens": self.total_input_tokens,
                    "output_tokens": self.total_output_tokens,
                    "duration_ms": int((time.time() - start_time) * 1000)
                }

            # 2. 处理生成的文件
            code_output = code_result.get("code_output", {})
            all_files = code_output.get("files", [])
            if not all_files:
                return {
                    "success": False,
                    "error": "No files generated by CoderAgent",
                    "output": None,
                    "attempt": attempt,
                    "input_tokens": self.total_input_tokens,
                    "output_tokens": self.total_output_tokens,
                    "duration_ms": int((time.time() - start_time) * 1000)
                }

            all_files, fix_report = ImportSanitizer.sanitize_files(all_files)

            # 路径防御
            for f in all_files:
                p = f.get("file_path", "")
                p = p.lstrip("/")
                if p and not p.startswith("backend/"):
                    f["file_path"] = f"backend/{p}"

            if fix_report:
                await push_log(
                    pipeline_id, "warning",
                    f"自动修正了 {len(fix_report)} 个文件的 import 路径",
                    stage="CODING"
                )
                code_output["files"] = all_files
                code_output["import_fixes"] = fix_report

            # 写入文件（带 Read Token 校验）
            try:
                await file_write_handler.write_files_to_project(all_files, pipeline_id)
                await self._write_files_to_sandbox(all_files, pipeline_id)
            except PermissionError as e:
                # 【Read Token 失效】文件可能被修改，需要重新读取
                logger.warning(f"[Pipeline {pipeline_id}] Read Token 失效，重新读取文件: {e}")
                await push_log(
                    pipeline_id, "warning",
                    f"文件已被修改，search_block 可能过时，正在重新读取...",
                    stage="CODING"
                )

                # 重新读取所有 affected_files 获取新的 read_token
                code_executor = CodeExecutorService()
                refreshed_files = {}
                for file_path in design_output.get("affected_files", []):
                    relative_path = file_path.replace("backend/", "").replace("backend\\", "")
                    read_result = code_executor.read_file(relative_path)
                    if read_result.exists and read_result.content:
                        refreshed_files[file_path] = read_result.content
                        logger.info(f"[Pipeline {pipeline_id}] 重新读取: {file_path}")

                if refreshed_files:
                    current_error_context = (
                        f"文件已被外部修改，read_token 失效。\n"
                        f"错误: {str(e)}\n"
                        f"请使用 read_file 工具重新读取以下文件，获取最新的 read_token：\n"
                        f"{list(refreshed_files.keys())}\n"
                        f"然后基于最新内容重新生成 search_block。"
                    )
                    attempt += 1
                    continue
                else:
                    raise

            # 3. 【阶段二：独立验证步骤】使用 VerifyAgent 进行验证
            verify_result = await self._verify_fixes(pipeline_id, all_files)

            if verify_result["verdict"] == "PASS":
                # 验证通过，退出循环
                await push_log(
                    pipeline_id,
                    "success",
                    "✅ 独立验证通过！AI 自动验证成功。",
                    stage="CODING"
                )

                # 启动预览服务器
                await self._start_preview_server(pipeline_id, sandbox_port)

                return {
                    "success": True,
                    "output": code_result["code_output"],
                    "attempt": attempt,
                    "input_tokens": self.total_input_tokens,
                    "output_tokens": self.total_output_tokens,
                    "duration_ms": int((time.time() - start_time) * 1000),
                    "preview_port": sandbox_port
                }

            elif verify_result["verdict"] == "FAIL":
                # 【利益隔离】RepairerAgent 修复阶段
                structured_errors = verify_result.get("structured_errors", {})

                await push_log(
                    pipeline_id, "warning",
                    f"📝 验证失败，生成修复工单并调用 RepairerAgent（第 {attempt + 1} 次修复）...",
                    stage="CODING"
                )

                # 【利益隔离】构建结构化工单
                failed_tests = verify_result.get("errors", [])
                evidence = verify_result.get("evidence", {})
                snippet = evidence.get("failed_output", "")[:1500]

                fix_order = {
                    "type": "fix_order",
                    "category": "code_bug",
                    "source": "VerificationAgent",
                    "errors": structured_errors.get("errors", []),
                    "failed_tests": failed_tests[:5],
                    "error_snippet": snippet,
                    "generated_files": [f.get("file_path", "") for f in all_files],
                    "fix_hint": "根据以上测试输出修复代码，务必使所有测试通过。"
                }

                await push_log(
                    pipeline_id, "info",
                    f"📋 修复工单已生成: {len(fix_order['errors'])} 个错误项",
                    stage="CODING"
                )

                # 【利益隔离核心】调用 RepairerAgent 进行修复
                repairer = RepairerAgent()
                repair_result = await repairer.execute_with_reread(
                    pipeline_id=pipeline_id,
                    stage_name="CODING_REPAIR",
                    fix_order=fix_order,
                    project_path=str(Path(settings.TARGET_PROJECT_PATH).resolve()),
                    initial_state={
                        "design_output": design_output,
                        "error_context": structured_errors,
                        "verification_report": {
                            "verdict": "FAIL",
                            "error_count": len(failed_tests),
                            "message": verify_result.get("message", "")
                        }
                    }
                )

                if not repair_result.get("success"):
                    logger.error(f"[Pipeline {pipeline_id}] RepairerAgent 修复失败")
                    await push_log(
                        pipeline_id, "error",
                        f"❌ RepairerAgent 修复失败: {repair_result.get('error', '未知错误')}",
                        stage="CODING"
                    )
                    attempt += 1
                    continue

                # 修复成功，更新 code_output
                repair_output = repair_result.get("output", {})
                if repair_output and "files" in repair_output:
                    all_files = repair_output["files"]
                    code_result["code_output"] = repair_output
                    logger.info(f"[Pipeline {pipeline_id}] RepairerAgent 修复完成，生成 {len(all_files)} 个文件修复")
                    await push_log(
                        pipeline_id, "info",
                        f"✅ RepairerAgent 修复完成，应用 {len(all_files)} 个文件修复",
                        stage="CODING"
                    )
                    await push_log(
                        pipeline_id, "info",
                        "🔄 修复已应用，将重新进行独立验证...",
                        stage="CODING"
                    )

                attempt += 1
                continue

        # 达到最大重试次数
        logger.error(f"AutoFixLoop: 自动修复达到最大次数", extra={
            "pipeline_id": pipeline_id,
            "max_retries": self.MAX_FIX_RETRIES,
            "total_input_tokens": self.total_input_tokens,
            "total_output_tokens": self.total_output_tokens
        })

        return {
            "success": False,
            "error": f"自动修复达到最大次数({self.MAX_FIX_RETRIES})，仍有测试未通过。",
            "last_error_logs": current_error_context,
            "attempt": attempt,
            "output": last_code_output,
            "input_tokens": self.total_input_tokens,
            "output_tokens": self.total_output_tokens,
            "duration_ms": int((time.time() - start_time) * 1000)
        }

    async def _execute_code_agent(
        self,
        design_output: Dict[str, Any],
        test_files: Dict[str, str],
        pipeline_id: Optional[int] = None,
        error_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """执行 CoderAgent"""
        from app.agents.coder import coder_agent

        logger.info(f"AutoFixLoop: 开始执行 CoderAgent", extra={
            "pipeline_id": pipeline_id,
            "affected_files": design_output.get("affected_files", []),
            "test_files_count": len(test_files)
        })

        # 构建增强的 design_output（包含测试文件参考）
        enhanced_design = self._build_coder_prompt_with_tests(design_output, {}, test_files)

        try:
            code_result = await coder_agent.generate_code(
                enhanced_design,
                pipeline_id,
                error_context=error_context
            )

            if code_result["success"]:
                return {
                    "success": True,
                    "code_output": code_result["output"],
                    "code_error": None,
                    "input_tokens": code_result.get("input_tokens", 0),
                    "output_tokens": code_result.get("output_tokens", 0),
                    "duration_ms": code_result.get("duration_ms", 0),
                }
            else:
                return {
                    "success": False,
                    "code_output": None,
                    "code_error": code_result["error"],
                    "input_tokens": code_result.get("input_tokens", 0),
                    "output_tokens": code_result.get("output_tokens", 0),
                    "duration_ms": code_result.get("duration_ms", 0),
                }
        except Exception as e:
            logger.error(f"AutoFixLoop: CoderAgent 执行异常", extra={
                "pipeline_id": pipeline_id,
                "error": str(e)
            })
            return {
                "success": False,
                "code_output": None,
                "code_error": f"CoderAgent execution failed: {str(e)}",
                "input_tokens": 0,
                "output_tokens": 0,
                "duration_ms": 0,
            }

    async def _read_test_files(
        self,
        pipeline_id: int,
        affected_files: List[str]
    ) -> Dict[str, str]:
        """根据 affected_files 读取对应的测试文件"""
        test_files = {}

        for file_path in affected_files:
            path_parts = file_path.split('/')
            if len(path_parts) < 2:
                continue

            file_name = path_parts[-1]
            module_name = file_name.replace('.py', '')

            possible_test_paths = [
                f"backend/tests/unit/test_{module_name}_api.py",
                f"backend/tests/unit/test_{module_name}.py",
                f"backend/tests/test_{module_name}.py",
            ]

            for test_path in possible_test_paths:
                try:
                    content = await read_file(pipeline_id, test_path)
                    if content:
                        test_files[test_path] = content
                        logger.info(f"读取测试文件成功: {test_path}", extra={
                            "pipeline_id": pipeline_id,
                            "test_file": test_path
                        })
                        break
                except Exception:
                    continue

        return test_files

    def _build_coder_prompt_with_tests(
        self,
        design_output: Dict[str, Any],
        target_files: Dict[str, str],
        test_files: Dict[str, str]
    ) -> Dict[str, Any]:
        """构建包含测试文件的 CoderAgent 输入"""
        if not test_files:
            return design_output

        enhanced_design = dict(design_output)
        enhanced_design["test_files_reference"] = {
            "description": "以下是对应的测试文件内容，供参考（绝对不能修改测试文件）",
            "files": {
                path: content[:3000]
                for path, content in test_files.items()
            }
        }

        return enhanced_design

    async def _write_files_to_sandbox(
        self,
        all_files: List[Dict[str, Any]],
        pipeline_id: int
    ) -> None:
        """写入文件到容器（用于实时预览）"""
        for file_change in all_files:
            await sandbox_write_file(
                pipeline_id=pipeline_id,
                path=file_change["file_path"],
                content=file_change["content"]
            )

    async def _verify_fixes(
        self,
        pipeline_id: int,
        all_files: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        【阶段二：独立验证步骤 - 利益隔离核心】

        独立的验证步骤，与修复者（RepairerAgent）完全分离。
        """
        logger.info(f"[Pipeline {pipeline_id}] 开始独立验证步骤（利益隔离）")
        await push_log(
            pipeline_id,
            "info",
            "🔍 独立验证步骤（VerifyAgent）- 只检测，不修复...",
            stage="CODING"
        )

        # 运行测试
        test_result = await self._run_tests_in_sandbox(pipeline_id)

        # 构建验证报告
        if test_result.get("success"):
            logger.info(f"[Pipeline {pipeline_id}] ✅ 验证通过")
            await push_log(
                pipeline_id,
                "success",
                "✅ Verification PASSED: 所有测试通过",
                stage="CODING"
            )
            return {
                "verdict": "PASS",
                "errors": [],
                "summary": "所有测试通过",
                "structured_errors": None,
                "message": "Verification PASSED: 所有测试通过。",
                "evidence": test_result.get("evidence", {})
            }

        # 测试失败，解析结构化错误
        logs = test_result.get("logs", "")
        error_type = test_result.get("error_type", "unknown")
        generated_files = [f.get("file_path", "") for f in all_files]

        structured_errors = parse_error_context(
            logs=logs,
            failure_cause=error_type,
            generated_files=generated_files
        )

        error_list = []
        for error in structured_errors.get("errors", []):
            file_path = error.get("file_path", "unknown")
            line = error.get("line", "?")
            summary = error.get("summary", "")
            error_list.append(f"[{file_path}:{line}] {summary}")

        logger.warning(f"[Pipeline {pipeline_id}] ❌ 验证失败: {len(error_list)} 个错误")
        await push_log(
            pipeline_id,
            "warning",
            f"❌ Verification FAILED: 发现 {len(error_list)} 个错误",
            stage="CODING",
            errors=error_list[:5]
        )

        return {
            "verdict": "FAIL",
            "errors": error_list,
            "summary": test_result.get("summary", "测试失败"),
            "structured_errors": structured_errors,
            "raw_logs": logs[:2000],
            "message": (
                "Verification FAILED: 代码未通过测试。以下是失败的测试清单和关键日志。"
                "请将本报告交还给修复系统，不要尝试修复。"
            ),
            "evidence": test_result.get("evidence", {})
        }

    async def _run_tests_in_sandbox(
        self,
        pipeline_id: int,
        test_files: Optional[List[Dict[str, Any]]] = None
    ) -> Dict[str, Any]:
        """在沙箱内运行测试（带智能重试）"""
        await push_log(
            pipeline_id,
            "info",
            "正在运行自动化测试验证（沙箱内）...",
            stage="CODING"
        )

        async def _do_run_tests():
            test_result_cmd = await exec_command(
                pipeline_id=pipeline_id,
                cmd="cd /workspace/backend && python -m pytest tests/ -v --tb=short --color=no -x 2>&1 | tail -100",
                timeout=120
            )
            return test_result_cmd

        try:
            test_result_cmd = await self._test_retry_executor.execute(_do_run_tests)
        except CircuitBreakerOpenError:
            await push_log(
                pipeline_id,
                "error",
                "测试服务暂时不可用，系统正在冷却，请稍后再试...",
                stage="CODING"
            )
            return {
                "success": False,
                "exit_code": -1,
                "logs": "Circuit breaker open",
                "summary": "测试服务暂时不可用",
                "error": "测试服务暂时不可用，系统正在冷却",
                "error_type": "circuit_breaker_open",
                "failed_tests": [],
                "is_test_file_error": False
            }
        except Exception as e:
            logger.error(f"Test execution failed after retries: {e}")
            await push_log(
                pipeline_id,
                "error",
                f"测试执行失败: {str(e)}",
                stage="CODING"
            )
            return {
                "success": False,
                "exit_code": -1,
                "logs": str(e),
                "summary": "测试执行失败",
                "error": str(e),
                "error_type": "execution_error",
                "failed_tests": [],
                "is_test_file_error": False
            }

        test_logs = test_result_cmd['stdout'] + test_result_cmd['stderr']
        test_success = test_result_cmd['exit_code'] == 0

        # 分析错误类型
        error_type = None
        failed_tests = []

        if not test_success:
            import re

            if "SyntaxError" in test_logs and "test_" in test_logs:
                error_type = "test_syntax_error"
            elif "ImportError" in test_logs or "ModuleNotFoundError" in test_logs:
                if "test_" in test_logs or "tests/" in test_logs:
                    error_type = "test_import_error"
                else:
                    error_type = "import_error"
            elif "collection error" in test_logs.lower() or "ImportError while loading" in test_logs:
                error_type = "test_collection_error"
            elif "FAILED" in test_logs or "failed" in test_logs.lower():
                error_type = "test_failure"
                failed_matches = re.findall(r'(\S+::\S+)\s+FAILED', test_logs)
                failed_tests = failed_matches
            elif "timeout" in test_logs.lower():
                error_type = "timeout"
            else:
                error_type = "unknown_error"

        return {
            "success": test_success,
            "exit_code": test_result_cmd['exit_code'],
            "logs": test_logs,
            "summary": "测试通过" if test_success else "测试失败",
            "error": None if test_success else test_logs[:500],
            "error_type": error_type,
            "failed_tests": failed_tests,
            "is_test_file_error": error_type in ["test_syntax_error", "test_import_error", "test_collection_error"] if error_type else False
        }

    async def _start_preview_server(
        self,
        pipeline_id: int,
        sandbox_port: Optional[int]
    ) -> bool:
        """启动预览服务器"""
        await push_log(
            pipeline_id,
            "info",
            "🚀 检查后端服务状态...",
            stage="CODING"
        )

        # 首先检查 8000 端口
        health_check_8000 = await exec_command(
            pipeline_id=pipeline_id,
            cmd="curl -s http://localhost:8000/api/v1/health 2>&1",
            timeout=5
        )

        if health_check_8000['exit_code'] == 0 and 'healthy' in health_check_8000['stdout']:
            await push_log(
                pipeline_id,
                "success",
                f"✅ 后端服务已在 8000 端口运行，可通过端口 {sandbox_port} 访问预览",
                stage="CODING"
            )
            return True

        # 如果 8000 端口没有服务，尝试在 8001 端口启动
        await push_log(
            pipeline_id,
            "info",
            "在 8001 端口启动后端服务...",
            stage="CODING"
        )

        await exec_command(
            pipeline_id=pipeline_id,
            cmd="cd /workspace/backend && python -m uvicorn app.main:app --host 0.0.0.0 --port 8001 --log-level info > /tmp/preview_server.log 2>&1 &",
            timeout=3
        )

        await asyncio.sleep(5)

        health_check = await exec_command(
            pipeline_id=pipeline_id,
            cmd="curl -s http://localhost:8001/api/v1/health 2>&1",
            timeout=10
        )

        if health_check['exit_code'] == 0 and 'healthy' in health_check['stdout']:
            await push_log(
                pipeline_id,
                "success",
                f"✅ 后端服务已启动，可通过端口 {sandbox_port} 访问预览",
                stage="CODING"
            )
            return True
        else:
            await push_log(
                pipeline_id,
                "warning",
                "⚠️ 后端服务启动可能有问题，但代码已生成",
                stage="CODING"
            )
            return False


# 单例实例
auto_fix_loop = AutoFixLoop()
